### ISSUE TITLE
HTML Tags don't have syntax color

### ISSUE THREAD

**Issue by alanfzf** [atelierbram/Base4Tone-nvim#1] opened 2022-11-09 04:06 UTC
It seems like there's no actual color syntax for html tags, i looked at the [demo](https://atelierbram.github.io/Base4Tone-prism/b4t_classic-f/dark/) and there's actual color syntax for html tags, so i don't know if this is a bug or the syntax highlighting for html is still being worked on. I leave a picture of how the color scheme looks inside a html file.
![color](https://user-images.githubusercontent.com/29936954/200735892-5896e54d-8a40-45e8-8a10-ac75156bb623.png)

**Comment by atelierbram** [comment] 2022-11-09 12:54
@alanfvn thanks for the feedback. I can't reproduce this. It should look something like the screenhot below.
Do you have Treesitter installed?

![](https://i.imgur.com/7XpIGBQ.png)

**Comment by alanfzf** [comment] 2022-11-09 19:14
Thanks for the reply, yeah, I'm actually using Treesitter, but it may have something to do with me using the latest commit, maybe there was some breaking changes.
![Screenshot 2022-11-09 130515](https://user-images.githubusercontent.com/29936954/200920540-489ac3dd-5e17-44cf-b0d6-42c494a2ef5d.png)

**Comment by atelierbram** [comment] 2022-11-09 19:58
@alanfvn I gave the HtmlTagName a different color because I realised it could be a bit more different, not really a breaking change though … but do you still get the same result now in HTML files after updating?

**Comment by alanfzf** [comment] 2022-11-09 20:04
oh, sorry i meant using Treesitter with the latest commit. I switched to branch v0.8.0 on Treesitter and this seems to have fixed, the syntax color issue
![Screenshot 2022-11-09 140322](https://user-images.githubusercontent.com/29936954/200929835-4c59322c-b3c9-4395-ab29-e685529ae2b3.png)

**Comment by atelierbram** [comment] 2022-11-09 20:09
OK glad to know, closing this issue now, take care!

**Closed as completed** 2022-11-09 20:09 UTC
